export const ALL_TEST_ITEMS = [
  { id: '6.3.1.2', clause: '6.3.1.2', name: '保护导体连续性的持续监测', requirement: '响应时间 < 100ms', standardHours: '0.5h' },
  { id: '6.3.1.3', clause: '6.3.1.3', name: '验证EV是否正确连接到EV供电设备', requirement: '正确识别连接状态', standardHours: '0.5h' },
  { id: '6.3.1.4', clause: '6.3.1.4', name: 'EV供电通电', requirement: '允许通电状态下才可供电', standardHours: '0.5h' },
  { id: '6.3.1.5', clause: '6.3.1.5', name: 'EV供电断电', requirement: '控制导引中断时切断电源', standardHours: '0.5h' },
  { id: '6.3.1.6', clause: '6.3.1.6', name: '最大允许电流', requirement: '不超过额定电流', standardHours: '1.0h' },
  { id: '8.1', clause: '8.1', name: 'EVSE的IP测试', requirement: '满足声明的IP等级', standardHours: '2.0h' },
  { id: '8.2.1', clause: '8.2.1', name: '插头连接的EV供电设备的断开', requirement: '断开后1s内电压<60V', standardHours: '1.0h' },
  { id: '8.2.2', clause: '8.2.2', name: '永久连接的EV供电设备的电源电压丢失', requirement: '断电后5s内电压<60V', standardHours: '1.0h' },
  { id: '8.3', clause: '8.3', name: '故障保护', requirement: '符合通用故障保护要求', standardHours: '1.5h' },
  { id: '11.6', clause: '11.6', name: '应力消除', requirement: '拉力测试后无损坏', standardHours: '1.0h' },
  { id: '11.7', clause: '11.7', name: '电缆组件的电缆管理和存储方式', requirement: '无过热，跌落无损坏', standardHours: '1.0h' },
  { id: '12.2.6', clause: '12.2.6', name: '浪涌电流', requirement: '承受规定的浪涌电流', standardHours: '1.0h' },
  { id: '12.3', clause: '12.3', name: '电气间隙和爬电距离', requirement: '满足基本/加强绝缘要求', standardHours: '2.0h' },
  { id: '12.4', clause: '12.4', name: 'IP等级', requirement: '防尘防水测试通过', standardHours: '4.0h' },
  { id: '12.5', clause: '12.5', name: '绝缘电阻', requirement: 'Class I > 1MΩ', standardHours: '0.5h' },
  { id: '12.6', clause: '12.6', name: '接触电流', requirement: '不超过限值', standardHours: '1.0h' },
  { id: '12.7.1', clause: '12.7.1', name: '交流耐压', requirement: '无击穿或闪络', standardHours: '1.0h' },
  { id: '12.7.2', clause: '12.7.2', name: '冲击耐压', requirement: '承受1.2/50µs冲击', standardHours: '1.0h' },
  { id: '12.8', clause: '12.8', name: '温升', requirement: '各部件温升不超限', standardHours: '4.0h' },
  { id: '12.9', clause: '12.9', name: '湿热功能测试', requirement: '湿热循环后功能正常', standardHours: '48.0h' },
  { id: '12.10', clause: '12.10', name: '最低温度功能测试', requirement: '低温下功能正常', standardHours: '16.0h' },
  { id: '12.11', clause: '12.11', name: '机械强度', requirement: 'IK08冲击后无损坏', standardHours: '1.0h' },
  { id: '13.2', clause: '13.2', name: '电缆组件的过载保护', requirement: '1.3倍电流1分钟内跳闸', standardHours: '1.0h' },
  { id: '13.3', clause: '13.3', name: '充电电缆的短路保护', requirement: 'I2t不超过限值', standardHours: '1.0h' },
  { id: '16.5', clause: '16.5', name: '标识耐久性测试', requirement: '擦拭后清晰可见', standardHours: '0.5h' },
  { id: 'annex_a', clause: 'Annex A', name: '控制导引电路导引功能', requirement: 'PWM及电压符合要求', standardHours: '2.0h' },
];
